import { Type, type Static } from "typebox";

import { ImageDataContent, TextContent } from "./contents";
import { ToolCall } from "./tools";

/**
 * The allowed content types of a user message.
 */
export const UserMessageContent = Type.Union([TextContent, ImageDataContent]);
export type UserMessageContent = TextContent | ImageDataContent;

/**
 * A message sent from user.
 */
export const UserMessage = Type.Object({
  /**
   * The unique ID of the message.
   */
  id: Type.String(),

  /**
   * The role of the message.
   */
  role: Type.Literal("user"),

  /**
   * The content of the message.
   */
  content: Type.Array(UserMessageContent),
});
export type UserMessage = Static<typeof UserMessage>;

/**
 * The allowed content types of a assistant message.
 */
export const AssistantMessageContent = Type.Union([TextContent]);

/**
 * A message generated by AI.
 */
export const AssistantMessage = Type.Object({
  /**
   * The unique ID of the message.
   */
  id: Type.String(),

  /**
   * The role of the message.
   */
  role: Type.Literal("assistant"),

  /**
   * The content of the message.
   */
  content: Type.Array(AssistantMessageContent),

  /**
   * The thinking of the message.
   */
  thinking: Type.Optional(Type.String()),

  /**
   * The tool calls of the message.
   */
  toolCalls: Type.Optional(Type.Array(ToolCall)),
});
export type AssistantMessage = Static<typeof AssistantMessage>;

/**
 * The union type of the message.
 */
export const Message = Type.Union([UserMessage, AssistantMessage]);
export type Message = UserMessage | AssistantMessage;
